// mobile-security : JWT token handling, Spring Security filter chain, user auth

plugins {
    id 'java'
    id 'io.spring.dependency-management'
}

repositories { mavenCentral() }

dependencies {
    implementation project(':mobile-common')
    implementation project(':mobile-data')
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"
}
