// mobile-api : REST controllers, Spring Boot entry point, OpenAPI docs

plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

repositories { mavenCentral() }

dependencies {
    implementation project(':mobile-common')
    implementation project(':mobile-security')
    implementation project(':mobile-data')
    implementation project(':mobile-business')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocOpenApiVersion}"
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
}

bootJar {
    archiveFileName = 'adproject-mobile-api.jar'
    layered { enabled = true }
}
